/* rubyplugin.vapi generated by valac 0.42.5, do not modify. */

[CCode (cheader_filename = "ext/src/rubyplugin.h")]
public class RubyPlugin : Xfce.PanelPlugin {
	public static RubyPlugin plugin;
	public RubyPlugin ();
	public override void @construct ();
	public static Gtk.EventBox @default ();
}
[CCode (cheader_filename = "ext/src/rubyplugin.h")]
[ModuleInit]
public static GLib.Type xfce_panel_module_init (GLib.TypeModule module);
